/*
Technitium API

Go SDK for interacting with Technitium APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 12.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package technitium

import (
	"encoding/json"
)

// checks if the GetZoneOptionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetZoneOptionsResponse{}

// GetZoneOptionsResponse Describes the result of processing a request
type GetZoneOptionsResponse struct {
	Response *GetZoneOptionsResponseResponse `json:"response,omitempty"`
	Status *string `json:"status,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetZoneOptionsResponse GetZoneOptionsResponse

// NewGetZoneOptionsResponse instantiates a new GetZoneOptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetZoneOptionsResponse() *GetZoneOptionsResponse {
	this := GetZoneOptionsResponse{}
	return &this
}

// NewGetZoneOptionsResponseWithDefaults instantiates a new GetZoneOptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetZoneOptionsResponseWithDefaults() *GetZoneOptionsResponse {
	this := GetZoneOptionsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *GetZoneOptionsResponse) GetResponse() GetZoneOptionsResponseResponse {
	if o == nil || IsNil(o.Response) {
		var ret GetZoneOptionsResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetZoneOptionsResponse) GetResponseOk() (*GetZoneOptionsResponseResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *GetZoneOptionsResponse) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given GetZoneOptionsResponseResponse and assigns it to the Response field.
func (o *GetZoneOptionsResponse) SetResponse(v GetZoneOptionsResponseResponse) {
	o.Response = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetZoneOptionsResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetZoneOptionsResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetZoneOptionsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetZoneOptionsResponse) SetStatus(v string) {
	o.Status = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *GetZoneOptionsResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetZoneOptionsResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *GetZoneOptionsResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *GetZoneOptionsResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o GetZoneOptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetZoneOptionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetZoneOptionsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetZoneOptionsResponse := _GetZoneOptionsResponse{}

	err = json.Unmarshal(data, &varGetZoneOptionsResponse)

	if err != nil {
		return err
	}

	*o = GetZoneOptionsResponse(varGetZoneOptionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "response")
		delete(additionalProperties, "status")
		delete(additionalProperties, "errorMessage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetZoneOptionsResponse struct {
	value *GetZoneOptionsResponse
	isSet bool
}

func (v NullableGetZoneOptionsResponse) Get() *GetZoneOptionsResponse {
	return v.value
}

func (v *NullableGetZoneOptionsResponse) Set(val *GetZoneOptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetZoneOptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetZoneOptionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetZoneOptionsResponse(val *GetZoneOptionsResponse) *NullableGetZoneOptionsResponse {
	return &NullableGetZoneOptionsResponse{value: val, isSet: true}
}

func (v NullableGetZoneOptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetZoneOptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


