/*
Technitium API

Go SDK for interacting with Technitium APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 12.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package technitium

import (
	"encoding/json"
)

// checks if the CreateRecordResponseResponseZone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRecordResponseResponseZone{}

// CreateRecordResponseResponseZone struct for CreateRecordResponseResponseZone
type CreateRecordResponseResponseZone struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Internal *bool `json:"internal,omitempty"`
	DnssecStatus *string `json:"dnssecStatus,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateRecordResponseResponseZone CreateRecordResponseResponseZone

// NewCreateRecordResponseResponseZone instantiates a new CreateRecordResponseResponseZone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRecordResponseResponseZone() *CreateRecordResponseResponseZone {
	this := CreateRecordResponseResponseZone{}
	return &this
}

// NewCreateRecordResponseResponseZoneWithDefaults instantiates a new CreateRecordResponseResponseZone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRecordResponseResponseZoneWithDefaults() *CreateRecordResponseResponseZone {
	this := CreateRecordResponseResponseZone{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateRecordResponseResponseZone) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordResponseResponseZone) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateRecordResponseResponseZone) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateRecordResponseResponseZone) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateRecordResponseResponseZone) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordResponseResponseZone) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateRecordResponseResponseZone) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateRecordResponseResponseZone) SetType(v string) {
	o.Type = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *CreateRecordResponseResponseZone) GetInternal() bool {
	if o == nil || IsNil(o.Internal) {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordResponseResponseZone) GetInternalOk() (*bool, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *CreateRecordResponseResponseZone) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *CreateRecordResponseResponseZone) SetInternal(v bool) {
	o.Internal = &v
}

// GetDnssecStatus returns the DnssecStatus field value if set, zero value otherwise.
func (o *CreateRecordResponseResponseZone) GetDnssecStatus() string {
	if o == nil || IsNil(o.DnssecStatus) {
		var ret string
		return ret
	}
	return *o.DnssecStatus
}

// GetDnssecStatusOk returns a tuple with the DnssecStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordResponseResponseZone) GetDnssecStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DnssecStatus) {
		return nil, false
	}
	return o.DnssecStatus, true
}

// HasDnssecStatus returns a boolean if a field has been set.
func (o *CreateRecordResponseResponseZone) HasDnssecStatus() bool {
	if o != nil && !IsNil(o.DnssecStatus) {
		return true
	}

	return false
}

// SetDnssecStatus gets a reference to the given string and assigns it to the DnssecStatus field.
func (o *CreateRecordResponseResponseZone) SetDnssecStatus(v string) {
	o.DnssecStatus = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *CreateRecordResponseResponseZone) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordResponseResponseZone) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *CreateRecordResponseResponseZone) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *CreateRecordResponseResponseZone) SetDisabled(v bool) {
	o.Disabled = &v
}

func (o CreateRecordResponseResponseZone) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRecordResponseResponseZone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.DnssecStatus) {
		toSerialize["dnssecStatus"] = o.DnssecStatus
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRecordResponseResponseZone) UnmarshalJSON(data []byte) (err error) {
	varCreateRecordResponseResponseZone := _CreateRecordResponseResponseZone{}

	err = json.Unmarshal(data, &varCreateRecordResponseResponseZone)

	if err != nil {
		return err
	}

	*o = CreateRecordResponseResponseZone(varCreateRecordResponseResponseZone)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "internal")
		delete(additionalProperties, "dnssecStatus")
		delete(additionalProperties, "disabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRecordResponseResponseZone struct {
	value *CreateRecordResponseResponseZone
	isSet bool
}

func (v NullableCreateRecordResponseResponseZone) Get() *CreateRecordResponseResponseZone {
	return v.value
}

func (v *NullableCreateRecordResponseResponseZone) Set(val *CreateRecordResponseResponseZone) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRecordResponseResponseZone) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRecordResponseResponseZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRecordResponseResponseZone(val *CreateRecordResponseResponseZone) *NullableCreateRecordResponseResponseZone {
	return &NullableCreateRecordResponseResponseZone{value: val, isSet: true}
}

func (v NullableCreateRecordResponseResponseZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRecordResponseResponseZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


