/*
Technitium API

Go SDK for interacting with Technitium APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 12.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package technitium

import (
	"encoding/json"
)

// checks if the ListZonesResponseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListZonesResponseResponse{}

// ListZonesResponseResponse struct for ListZonesResponseResponse
type ListZonesResponseResponse struct {
	PageNumber *int32 `json:"pageNumber,omitempty"`
	TotalPages *int32 `json:"totalPages,omitempty"`
	TotalZones *int32 `json:"totalZones,omitempty"`
	Zones []ListZonesResponseResponseZonesInner `json:"zones,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListZonesResponseResponse ListZonesResponseResponse

// NewListZonesResponseResponse instantiates a new ListZonesResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListZonesResponseResponse() *ListZonesResponseResponse {
	this := ListZonesResponseResponse{}
	return &this
}

// NewListZonesResponseResponseWithDefaults instantiates a new ListZonesResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListZonesResponseResponseWithDefaults() *ListZonesResponseResponse {
	this := ListZonesResponseResponse{}
	return &this
}

// GetPageNumber returns the PageNumber field value if set, zero value otherwise.
func (o *ListZonesResponseResponse) GetPageNumber() int32 {
	if o == nil || IsNil(o.PageNumber) {
		var ret int32
		return ret
	}
	return *o.PageNumber
}

// GetPageNumberOk returns a tuple with the PageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListZonesResponseResponse) GetPageNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.PageNumber) {
		return nil, false
	}
	return o.PageNumber, true
}

// HasPageNumber returns a boolean if a field has been set.
func (o *ListZonesResponseResponse) HasPageNumber() bool {
	if o != nil && !IsNil(o.PageNumber) {
		return true
	}

	return false
}

// SetPageNumber gets a reference to the given int32 and assigns it to the PageNumber field.
func (o *ListZonesResponseResponse) SetPageNumber(v int32) {
	o.PageNumber = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *ListZonesResponseResponse) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListZonesResponseResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *ListZonesResponseResponse) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *ListZonesResponseResponse) SetTotalPages(v int32) {
	o.TotalPages = &v
}

// GetTotalZones returns the TotalZones field value if set, zero value otherwise.
func (o *ListZonesResponseResponse) GetTotalZones() int32 {
	if o == nil || IsNil(o.TotalZones) {
		var ret int32
		return ret
	}
	return *o.TotalZones
}

// GetTotalZonesOk returns a tuple with the TotalZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListZonesResponseResponse) GetTotalZonesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalZones) {
		return nil, false
	}
	return o.TotalZones, true
}

// HasTotalZones returns a boolean if a field has been set.
func (o *ListZonesResponseResponse) HasTotalZones() bool {
	if o != nil && !IsNil(o.TotalZones) {
		return true
	}

	return false
}

// SetTotalZones gets a reference to the given int32 and assigns it to the TotalZones field.
func (o *ListZonesResponseResponse) SetTotalZones(v int32) {
	o.TotalZones = &v
}

// GetZones returns the Zones field value if set, zero value otherwise.
func (o *ListZonesResponseResponse) GetZones() []ListZonesResponseResponseZonesInner {
	if o == nil || IsNil(o.Zones) {
		var ret []ListZonesResponseResponseZonesInner
		return ret
	}
	return o.Zones
}

// GetZonesOk returns a tuple with the Zones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListZonesResponseResponse) GetZonesOk() ([]ListZonesResponseResponseZonesInner, bool) {
	if o == nil || IsNil(o.Zones) {
		return nil, false
	}
	return o.Zones, true
}

// HasZones returns a boolean if a field has been set.
func (o *ListZonesResponseResponse) HasZones() bool {
	if o != nil && !IsNil(o.Zones) {
		return true
	}

	return false
}

// SetZones gets a reference to the given []ListZonesResponseResponseZonesInner and assigns it to the Zones field.
func (o *ListZonesResponseResponse) SetZones(v []ListZonesResponseResponseZonesInner) {
	o.Zones = v
}

func (o ListZonesResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListZonesResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageNumber) {
		toSerialize["pageNumber"] = o.PageNumber
	}
	if !IsNil(o.TotalPages) {
		toSerialize["totalPages"] = o.TotalPages
	}
	if !IsNil(o.TotalZones) {
		toSerialize["totalZones"] = o.TotalZones
	}
	if !IsNil(o.Zones) {
		toSerialize["zones"] = o.Zones
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListZonesResponseResponse) UnmarshalJSON(data []byte) (err error) {
	varListZonesResponseResponse := _ListZonesResponseResponse{}

	err = json.Unmarshal(data, &varListZonesResponseResponse)

	if err != nil {
		return err
	}

	*o = ListZonesResponseResponse(varListZonesResponseResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pageNumber")
		delete(additionalProperties, "totalPages")
		delete(additionalProperties, "totalZones")
		delete(additionalProperties, "zones")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListZonesResponseResponse struct {
	value *ListZonesResponseResponse
	isSet bool
}

func (v NullableListZonesResponseResponse) Get() *ListZonesResponseResponse {
	return v.value
}

func (v *NullableListZonesResponseResponse) Set(val *ListZonesResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListZonesResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListZonesResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListZonesResponseResponse(val *ListZonesResponseResponse) *NullableListZonesResponseResponse {
	return &NullableListZonesResponseResponse{value: val, isSet: true}
}

func (v NullableListZonesResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListZonesResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


