/*
Technitium API

Go SDK for interacting with Technitium APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 12.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package technitium

import (
	"encoding/json"
)

// checks if the CreateZoneResponseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateZoneResponseResponse{}

// CreateZoneResponseResponse struct for CreateZoneResponseResponse
type CreateZoneResponseResponse struct {
	Domain *string `json:"domain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateZoneResponseResponse CreateZoneResponseResponse

// NewCreateZoneResponseResponse instantiates a new CreateZoneResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateZoneResponseResponse() *CreateZoneResponseResponse {
	this := CreateZoneResponseResponse{}
	return &this
}

// NewCreateZoneResponseResponseWithDefaults instantiates a new CreateZoneResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateZoneResponseResponseWithDefaults() *CreateZoneResponseResponse {
	this := CreateZoneResponseResponse{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CreateZoneResponseResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateZoneResponseResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CreateZoneResponseResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CreateZoneResponseResponse) SetDomain(v string) {
	o.Domain = &v
}

func (o CreateZoneResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateZoneResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateZoneResponseResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateZoneResponseResponse := _CreateZoneResponseResponse{}

	err = json.Unmarshal(data, &varCreateZoneResponseResponse)

	if err != nil {
		return err
	}

	*o = CreateZoneResponseResponse(varCreateZoneResponseResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateZoneResponseResponse struct {
	value *CreateZoneResponseResponse
	isSet bool
}

func (v NullableCreateZoneResponseResponse) Get() *CreateZoneResponseResponse {
	return v.value
}

func (v *NullableCreateZoneResponseResponse) Set(val *CreateZoneResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateZoneResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateZoneResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateZoneResponseResponse(val *CreateZoneResponseResponse) *NullableCreateZoneResponseResponse {
	return &NullableCreateZoneResponseResponse{value: val, isSet: true}
}

func (v NullableCreateZoneResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateZoneResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


